### ISSUE TITLE
Console Spam On Login

### ISSUE THREAD

**Issue by EZKatnipz** [BrainStone/InvSync#11]
#### Issue Description:
Basically, after installing the plugin, without doing anything to it in the config, and logging into the server, it just constantly throws the same error, over and over very rapidly.
Nothing else, really. After putting the mod into the server and logging in, i noticed the TPS was down to about 3 or so, and i checked the console and it was just this error.

First was trying to use with Pixelmon, but also tested in a server with just Sponge and InvSync.

Produces error with default settings and after changing database file path.

#### Affected Versions:

- Minecraft: 1.10.2
- InvSync: InvSync-0.5.19-beta
- Sponge: spongeforge-1.10.2-2281-5.2.0-BETA-2300

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/Gj0UaZ32

**Comment by BrainStone** [comment]
I think I see the issue. Try using version 0.5.10 for now. That should not have the issue.

**Comment by BrainStone** [comment]
The next release will contain the fix as well!

**Comment by BrainStone** [comment]
Or use the current development version: https://gitlab.brainstonemod.com/BrainStone/InvSync/builds/3729/artifacts/file/InvSync-0.5.26-beta.jar
